# -*- coding: utf-8 -*-
"""Assignment 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16ZqfAA04VfiUERHcXy7hxGARTehEQozs
"""

#Enter first and last name
firstname = input("Enter first name ")

lastname = input("Enter last name ")


#Enter your goals for this class
print("What are your goals for this class - long term goals?")
goals = input('What would you like to be....when all is said and done with the class?')
print()
print("First Name: " + firstname + " Last Name: " + lastname)
print(goals)